# Elsevier configuration

executor:
  publisher_name: elsevier
  res_type: metadata
  resource_dir: /Users/giorgio/Desktop/dit
  metadata_dir: resourcesync/elsevier/metadata
  url_prefix: http://giorgios-macbook-pro.local:8888
  max_items_in_list: 50000
  zero_fill_filename: 4
  is_saving_pretty_xml: True
  is_saving_sitemaps: True
  has_wellknown_at_root: True
  description_dir: /Users/giorgio/Desktop/dit
  elastic_host: localhost
  elastic_port: 9200
  elastic_index: resourcesync
  elastic_resource_type: resource
  elastic_change_type: change